baseurl: http://www2.cs.sfu.ca/~mwhitney/personal/test/jekyll/_site/
permalink: posts/:year-:month-:day-:title
featured:
  list_file: featured
bibtex:
  file: publications.bib
  out_skip_keys: url abstract
  bibtex_skip_keys: abstract
  sort_keys: -year order
  page_dir: publications
  page_layout: publication
