permalink: posts/:year-:month-:day-:title
featured:
  list_file: featured
bibtex:
  file: publications.bib
  out_skip_keys: url abstract
  bibtex_skip_keys: abstract
  sort_keys: -year order
  page_dir: publications
  page_layout: publication
  in_default_bib_type: inbib
  append_ref: " <ul class=\"publicationlinks\">{% if item.url %}<li><a href=\"{{ item.url }}\">URL</a></li>{% endif %}{% if item.pdf %}<li><a href=\"{{ item.pdf }}\">PDF</a></li>{% endif %}{% if item.pageurl %}<li><a href=\"{{ site.baseurl }}{{ item.pageurl }}\">More</a> (<a href=\"{{ site.baseurl }}{{ item.pageurl }}#bibtex\">Bibtex</a>{% if item.abstract %}, <a href=\"{{ site.baseurl }}{{ item.pageurl }}#abstract\">abstract</a>{% endif %})</li>{% endif %}</ul>"
